### PR TITLE
Fix #25: One of {message,formattedRuleMessage} is required

### LINKED ISSUE #25: One of result.{message,formattedRuleMessage} is required
Copied from https://github.com/sarif-standard/sarif-spec/issues/259, created by @lgolding:

The section on [`result.formattedRuleMessage`](https://rawgit.com/sarif-standard/sarif-spec/master/Static%20Analysis%20Results%20Interchange%20Format%20%28SARIF%29.html#result-formattedrulemessage) correctly says:

> If the formattedRuleMessage property is present on a result, the message property (Sec. 5.14.5) shall be absent. If the message property is present on a result, the formattedRuleMessage property shall be absent.

But the section on [`result.message`](https://rawgit.com/sarif-standard/sarif-spec/master/Static%20Analysis%20Results%20Interchange%20Format%20%28SARIF%29.html#result-message) inconsistently says that `result.message` _shall_ be present.

### PR DESCRIPTION
**Pull request by lgolding**
This fixes an inconsistency in wording between Section 3.17.5 (the `result.message` property) and Section 3.17.6 (the `result.formattedRuleMessage` property). Section 3.17.6 was correct: only one of those two properties can be present in a given result.

@michaelcfanning The proposed wording change is in Section 3.17.5 in ChangeDrafts\sarif-v1.0-issue-25-message-formattedRuleMessage.docx. You'll need to download the document to see it.

If you approve this, I'll merge the change into ProvisionalDrafts\sarif-v1.0-wd02-provisional.docx (per our workflow), add that change to this PR, and then merge the PR (which will result in closing the issue).

### CODE REVIEW

**Comment by michaelcfanning** [comment]
Why are we not permitting both the 'message' and 'formattedMessage' to be populated? It seems a bit harsh to forbid this. I assume you are concerned about possible discrepancies using the message vs. building a formattedMessage and/or having to provide advice on which to prefer. We can avoid these issues simply by noting that if both are present, the formattedMessage, when actually formatted using data in the log file, should be identical to the fully constructed 'message' property.

One reason both might be present is in cases where a tool (such as the multi-tool) has 'flattened' a log file in order to maximize its readability. We haven't actually authored this verb in the tool yet, but it has been discussed.

**Comment by DerSaidin** [comment]
> We can avoid these issues simply by noting that if both are present, the formattedMessage, when actually formatted using data in the log file, should be identical to the fully constructed 'message' property.

This makes sense to me.

Would it need to specify how a URL would need to appear in the unformatted message? Just the text? Optionally followed by the URL (or source location description for internal links to files) in parentheses?

**Comment by lgolding** [comment]
@DerSaidin Andrew, sorry for the confusion in terminology. The "`result.formattedRuleMessage`" property --
 which has been part of SARIF from the beginning, before we ever considered support for Markdown or HTML in message text -- is simply a plain-text string with substitution sequences (for example, `"The meaning of life is {0}, not {1}."`), together with an array of arguments to insert in place of the substitution sequences (for example, `[ "42", "54" ]`). See Section 3.17.6, "formattedRuleMessage property", and Section 3.28, "formattedMessage object".

That's why, when I started writing the spec-ese that proposed supporting Markdown, I had to invent a new term ("message with formatting") to describe a message string that includes Markdown.

With that in mind, URLs can appear in both `result.message` text and in `result.formattedRuleMessage` however the author of the analysis tool wishes. For example:

```
"runs": [
  "results": [
    {
      "ruleId": "EX0001",
      "message": "Never visit the URL http://www.evil.com (Evil Corp home page)",
      "formattedRuleMessage": {
        "formatId": "default",
        "arguments": [
          "http://www.evil.com",
          "Evil Corp home page"
        ]
      }
    }
  ],

  "rules": {
    "EX0001": {
      "id": "EX0001",
      "messageFormats": {
        "default": "Never visit the URL {0} ({1})"
      }
    }
  }
]
```

**Comment by lgolding** [comment]
Merging this change so that the change draft is available on the master branch. According to the Workflow, I should never have opened a PR for this in the first place.

**Pull request merged**
